INSERT INTO states (name) VALUES ('Abia');
INSERT INTO states (name) VALUES ('Abuja Federal Capital Territory');
INSERT INTO states (name) VALUES ('Adamawa');
INSERT INTO states (name) VALUES ('Akwa Ibom');
INSERT INTO states (name) VALUES ('Anambra');
INSERT INTO states (name) VALUES ('Bauchi');
INSERT INTO states (name) VALUES ('Bayelsa');
INSERT INTO states (name) VALUES ('Benue');
INSERT INTO states (name) VALUES ('Borno');
INSERT INTO states (name) VALUES ('Cross River');
INSERT INTO states (name) VALUES ('Delta');
INSERT INTO states (name) VALUES ('Ebonyi');
INSERT INTO states (name) VALUES ('Edo');
INSERT INTO states (name) VALUES ('Ekiti');
INSERT INTO states (name) VALUES ('Enugu');
INSERT INTO states (name) VALUES ('Gombe');
INSERT INTO states (name) VALUES ('Imo');
INSERT INTO states (name) VALUES ('Jigawa');
INSERT INTO states (name) VALUES ('Kaduna');
INSERT INTO states (name) VALUES ('Kano');
INSERT INTO states (name) VALUES ('Katsina');
INSERT INTO states (name) VALUES ('Kebbi');
INSERT INTO states (name) VALUES ('Kogi');
INSERT INTO states (name) VALUES ('Kwara');
INSERT INTO states (name) VALUES ('Lagos');
INSERT INTO states (name) VALUES ('Nassarawa');
INSERT INTO states (name) VALUES ('Niger');
INSERT INTO states (name) VALUES ('Ogun');
INSERT INTO states (name) VALUES ('Ondo');
INSERT INTO states (name) VALUES ('Osun');
INSERT INTO states (name) VALUES ('Oyo');
INSERT INTO states (name) VALUES ('Plateau');
INSERT INTO states (name) VALUES ('Rivers');
INSERT INTO states (name) VALUES ('Sokoto');
INSERT INTO states (name) VALUES ('Taraba');
INSERT INTO states (name) VALUES ('Yobe');
INSERT INTO states (name) VALUES ('Zamfara');
INSERT INTO users (name, code) VALUES ('Wisdom Emenike', '40dr0ce');
